# Generated by Django 3.1.7 on 2021-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='users',
            name='real_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='selected_course',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
