# Generated by Django 3.1.7 on 2021-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210311_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='账号创建时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='*电子邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='*用户名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256, verbose_name='*密码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='real_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='selected_course',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='已选课程'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='*性别'),
        ),
    ]
