# Generated by Django 3.1.7 on 2021-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210311_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='删除标记'),
        ),
    ]
