# Generated by Django 3.1.7 on 2021-03-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210311_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar/default-profile-picture.jpg', null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
