# Generated by Django 3.1.7 on 2021-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210313_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='access',
            field=models.CharField(choices=[('guest', '访客'), ('student', '学生'), ('teacher', '教师')], default='访客', max_length=16, verbose_name='权限等级'),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
