# Generated by Django 3.1.7 on 2021-03-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210325_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=64, verbose_name='课程名称')),
                ('Course_Teacher', models.CharField(max_length=32, verbose_name='开课教师')),
                ('Course_Info', models.CharField(max_length=400, verbose_name='课程说明')),
                ('Course_Img', models.ImageField(blank=True, null=True, upload_to='Course_Img', verbose_name='课程图片')),
                ('Stu_Count', models.IntegerField(verbose_name='选课人数')),
                ('Course_Faculty', models.CharField(max_length=32, verbose_name='课程分类')),
                ('View_Count', models.IntegerField(verbose_name='访问人数')),
                ('Status', models.CharField(choices=[('1', '未开课'), ('2', '已开课'), ('3', '已结课')], default='1', max_length=16, verbose_name='课程状态')),
                ('Starting_Time', models.DateTimeField(auto_now_add=True, verbose_name='开课时间')),
                ('Ending_Time', models.DateTimeField(verbose_name='结课时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-Starting_Time'],
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='access',
            field=models.CharField(choices=[('guest', '访客'), ('student', '学生'), ('teacher', '教师')], default='guest', max_length=16, verbose_name='*权限等级'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('default', '保密')], default='default', max_length=32, verbose_name='*性别'),
        ),
    ]
