# Generated by Django 3.1.7 on 2021-04-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210327_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Course_Faculty',
        ),
        migrations.AddField(
            model_name='course',
            name='Course_Category',
            field=models.CharField(default='0', max_length=32, verbose_name='课程分类'),
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False, verbose_name='分类编号')),
                ('CategoryName', models.CharField(max_length=64, verbose_name='分类名')),
                ('CountNumber', models.IntegerField(default=0, verbose_name='下属分类数')),
                ('ParentID', models.ForeignKey(default='0', limit_choices_to={'ParentID': 0}, on_delete=django.db.models.deletion.CASCADE, to='index.coursecategory')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'ordering': ['-CategoryID'],
            },
        ),
    ]
