# Generated by Django 3.1.7 on 2021-04-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210418_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='ParentID',
            field=models.ForeignKey(blank=True, default='0', limit_choices_to={'ParentID': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.coursecategory'),
        ),
    ]
