# Generated by Django 3.1.7 on 2021-04-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20210418_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='Is_Root',
            field=models.IntegerField(default=1, editable=False, max_length=8, verbose_name='第一级分类'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='ParentID',
            field=models.ForeignKey(blank=True, limit_choices_to={'Is_Root': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.coursecategory'),
        ),
    ]
