# Generated by Django 3.1.7 on 2021-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20210418_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='Is_Root',
            field=models.IntegerField(default=1, editable=False, verbose_name='第一级分类'),
        ),
    ]
