# Generated by Django 3.1.7 on 2021-04-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20210418_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='CountNumber',
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='Is_Root',
            field=models.BooleanField(default=True, verbose_name='第一级分类'),
        ),
    ]
