# Generated by Django 3.1.7 on 2021-04-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20210420_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='DisplayOrder',
            field=models.IntegerField(default=1, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='Is_Root',
            field=models.BooleanField(default=True, editable=False, verbose_name='根分类'),
        ),
    ]
