# Generated by Django 3.1.7 on 2021-04-21 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210420_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Category',
            field=models.ForeignKey(blank=True, limit_choices_to={'Is_Root': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.coursecategory'),
        ),
    ]
