# Generated by Django 3.1.7 on 2021-04-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20210421_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Chapter',
            field=models.JSONField(null=True, verbose_name='课程章节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Info',
            field=models.CharField(max_length=800, verbose_name='课程说明'),
        ),
        migrations.AlterField(
            model_name='users',
            name='access',
            field=models.CharField(choices=[('banned', '封禁用户'), ('guest', '访客'), ('student', '学生'), ('teacher', '教师')], default='guest', max_length=16, verbose_name='*权限等级'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(editable=False, max_length=256, verbose_name='*密码'),
        ),
    ]
