# Generated by Django 3.1.7 on 2021-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20210425_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Name',
            field=models.CharField(db_column='课程名称', max_length=64),
        ),
    ]
