# Generated by Django 3.1.7 on 2021-04-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20210426_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Name',
            field=models.CharField(max_length=64, verbose_name='课程名称'),
        ),
    ]
