# Generated by Django 3.1.7 on 2021-04-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20210426_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Img',
            field=models.ImageField(blank=True, default='material/defaultCourseImage.jpg', null=True, upload_to='Course_Img', verbose_name='课程图片'),
        ),
    ]
