# Generated by Django 3.1.7 on 2021-04-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20210427_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Chapter',
            field=models.JSONField(blank=True, null=True, verbose_name='课程章节'),
        ),
    ]
