# Generated by Django 3.1.7 on 2021-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20210427_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Info',
            field=models.TextField(verbose_name='课程说明'),
        ),
    ]
