# Generated by Django 3.1.7 on 2021-04-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20210428_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Goal',
            field=models.TextField(default='暂未设置', verbose_name='课程目标'),
        ),
        migrations.AddField(
            model_name='course',
            name='Grade_Requirements',
            field=models.TextField(default='暂未设置', verbose_name='成绩要求'),
        ),
        migrations.AddField(
            model_name='course',
            name='QA',
            field=models.JSONField(blank=True, null=True, verbose_name='常见问题'),
        ),
        migrations.AddField(
            model_name='course',
            name='Reference',
            field=models.TextField(default='暂未设置', verbose_name='参考资料'),
        ),
    ]
