# Generated by Django 3.1.7 on 2021-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20210428_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Goal',
            field=models.TextField(db_column='课程目标', default='暂未设置'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Info',
            field=models.TextField(db_column='课程说明'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Grade_Requirements',
            field=models.TextField(db_column='成绩要求', default='暂未设置'),
        ),
        migrations.AlterField(
            model_name='course',
            name='QA',
            field=models.JSONField(blank=True, db_column='常见问题', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Reference',
            field=models.TextField(db_column='参考资料', default='暂未设置'),
        ),
    ]
