# Generated by Django 3.1.7 on 2021-05-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20210428_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'access': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.users'),
        ),
    ]
