# Generated by Django 3.1.7 on 2021-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20210502_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='selected_course',
        ),
        migrations.AddField(
            model_name='users',
            name='selected_courses',
            field=models.ManyToManyField(to='index.Course'),
        ),
    ]
