# Generated by Django 3.1.7 on 2021-05-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20210512_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='selected_courses',
            field=models.ManyToManyField(to='index.CourseCategory'),
        ),
    ]
