# Generated by Django 3.1.7 on 2021-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20210512_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='selected_courses',
            field=models.ManyToManyField(to='index.Course'),
        ),
    ]
