# Generated by Django 3.1.7 on 2021-05-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20210512_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Chapter',
            field=models.JSONField(blank=True, default='暂未设置', null=True, verbose_name='课程章节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Info',
            field=models.TextField(default='暂未设置', verbose_name='课程说明'),
        ),
        migrations.AlterField(
            model_name='course',
            name='QA',
            field=models.JSONField(blank=True, default='暂未设置', null=True, verbose_name='常见问题'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Stu_Count',
            field=models.PositiveIntegerField(default=0, verbose_name='选课人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='View_Count',
            field=models.PositiveIntegerField(default=0, verbose_name='访问人数'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='DisplayOrder',
            field=models.PositiveIntegerField(default=1, verbose_name='显示顺序'),
        ),
    ]
