# Generated by Django 3.1.7 on 2021-05-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_auto_20210513_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Chapter',
            field=models.TextField(blank=True, default='[{"title":"New Node","key":"1"}]', null=True, verbose_name='课程章节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='QA',
            field=models.TextField(blank=True, default='暂未设置', null=True, verbose_name='常见问题'),
        ),
    ]
