# Generated by Django 3.1.7 on 2021-05-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_auto_20210523_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Category',
            field=models.ForeignKey(blank=True, limit_choices_to={'Is_Root': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.coursecategory', verbose_name='课程分类'),
        ),
    ]
