# Generated by Django 3.1.7 on 2021-05-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_auto_20210523_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='selected_courses',
            field=models.ManyToManyField(related_name='students', to='index.Course'),
        ),
    ]
