# Generated by Django 3.1.7 on 2021-06-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_auto_20210526_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'access': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='index.users'),
        ),
    ]
