# Generated by Django 3.1.7 on 2021-06-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_auto_20210604_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='开课了!', max_length=20, verbose_name='公告标题')),
                ('Message', models.TextField(default='欢迎参加本课程!', verbose_name='课程公告')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('sourceCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourceCourse', to='index.course', verbose_name='源课程')),
            ],
        ),
    ]
