# Generated by Django 3.1.7 on 2021-06-07 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_courseannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='新公告标题', max_length=20, verbose_name='公告标题')),
                ('Message', models.TextField(default='新公告内容', verbose_name='课程公告')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('sourceCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourceCourse', to='index.course', verbose_name='源课程')),
            ],
            options={
                'verbose_name': '课程公告',
                'verbose_name_plural': '课程公告',
                'ordering': ['-createTime'],
            },
        ),
        migrations.DeleteModel(
            name='CourseAnnouncement',
        ),
    ]
