# Generated by Django 3.1.7 on 2021-06-14 15:47

from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_auto_20210607_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterName', models.CharField(max_length=100, verbose_name='章名')),
                ('sourceCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapterSourceCourse', to='index.course', verbose_name='源课程')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=100, verbose_name='节名')),
                ('courseFile', models.FileField(upload_to=index.models.Upload_File_Path)),
                ('sourceChapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceChapter', to='index.chapter', verbose_name='所属章')),
            ],
        ),
    ]
