# Generated by Django 3.1.7 on 2022-03-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_auto_20210615_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefiles',
            name='fileName',
            field=models.CharField(default='新课件', max_length=100, verbose_name='课件名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Ending_Time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结课时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='selected_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='index.Course'),
        ),
    ]
