# Generated by Django 3.1.7 on 2022-03-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_auto_20220314_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionName', models.CharField(max_length=200, verbose_name='题目名称')),
                ('QuestionType', models.CharField(max_length=20, verbose_name='题目类型')),
                ('QuestionScore', models.PositiveIntegerField(default=0, verbose_name='题目分值')),
                ('ReferenceCount', models.PositiveIntegerField(default=0, verbose_name='引用次数')),
                ('PublicRelease', models.BooleanField(default=False, verbose_name='是否公开')),
                ('sourceCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionSourceCourse', to='index.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.AlterModelOptions(
            name='coursefiles',
            options={'ordering': ['sourceSection'], 'verbose_name': '课程文件', 'verbose_name_plural': '课程文件'},
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionName', models.CharField(max_length=100, verbose_name='选项')),
                ('sourceQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionSourceQuestion', to='index.questionbank', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=100, verbose_name='答案')),
                ('sourceOption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerSourceOption', to='index.questionoption', verbose_name='所属选项')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperName', models.CharField(max_length=100, verbose_name='试卷名称')),
                ('PaperType', models.CharField(max_length=20, verbose_name='试卷类型')),
                ('QuestionCount', models.PositiveIntegerField(default=0, verbose_name='题目数量')),
                ('ExaminationTime', models.TimeField(verbose_name='考试时间')),
                ('QuestionTotalScore', models.PositiveIntegerField(default=0, verbose_name='试卷总分')),
                ('StartTime', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('EndTime', models.DateTimeField(verbose_name='结束时间')),
                ('includedQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paperIncludedQuestion', to='index.questionbank', verbose_name='包含题目')),
                ('sourceCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paperSourceCourse', to='index.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='AnsweredPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperCandidates', to='index.users', verbose_name='考生')),
                ('sourcePaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answeredPaperSourcePaper', to='index.paper', verbose_name='所属试卷')),
            ],
        ),
    ]
