# Generated by Django 4.0.3 on 2022-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_auto_20220325_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='includedQuestion',
        ),
        migrations.AddField(
            model_name='paper',
            name='includedQuestions',
            field=models.ManyToManyField(related_name='paperIncludedQuestion', to='index.questionbank', verbose_name='包含题目'),
        ),
    ]
