# Generated by Django 4.0.3 on 2022-04-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_remove_paper_includedquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='includedQuestions',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='sourceCourse',
        ),
        migrations.DeleteModel(
            name='AnsweredPaper',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
