# Generated by Django 4.0.3 on 2022-04-05 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_remove_paper_includedquestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperName', models.CharField(max_length=100, verbose_name='试卷名称')),
                ('PaperType', models.CharField(max_length=20, verbose_name='试卷类型')),
                ('QuestionCount', models.PositiveIntegerField(default=0, verbose_name='题目数量')),
                ('ExaminationTime', models.TimeField(verbose_name='考试时间')),
                ('QuestionTotalScore', models.PositiveIntegerField(default=0, verbose_name='试卷总分')),
                ('StartTime', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('EndTime', models.DateTimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='PaperQuestionsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionScore', models.PositiveIntegerField(default=0, verbose_name='题目分值')),
                ('sourcePaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.paper')),
                ('sourceQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.questionbank')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='includedQuestions',
            field=models.ManyToManyField(related_name='paperIncludedQuestion', through='index.PaperQuestionsInformation', to='index.questionbank', verbose_name='包含题目'),
        ),
        migrations.AddField(
            model_name='paper',
            name='sourceCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paperSourceCourse', to='index.course', verbose_name='所属课程'),
        ),
        migrations.CreateModel(
            name='AnsweredPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperCandidates', to='index.users', verbose_name='考生')),
                ('sourcePaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answeredPaperSourcePaper', to='index.paper', verbose_name='所属试卷')),
            ],
        ),
    ]
