# Generated by Django 4.0.3 on 2022-04-06 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0042_paper_paperquestionsinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='StartTime',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='sourceQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answers', to='index.questionbank', verbose_name='所属题目'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='sourceCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='index.course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='sourceQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Options', to='index.questionbank', verbose_name='所属题目'),
        ),
    ]
