# Generated by Django 4.0.3 on 2022-04-13 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0044_alter_paper_papertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedOption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.questionoption')),
            ],
        ),
        migrations.AddField(
            model_name='answeredpaper',
            name='Answersheet',
            field=models.ManyToManyField(related_name='Answersheet', through='index.AnswerSheet', to='index.questionoption', verbose_name='答题卡'),
        ),
        migrations.AddField(
            model_name='answeredpaper',
            name='EndTime',
            field=models.DateTimeField(default=None, verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answeredpaper',
            name='Score',
            field=models.PositiveIntegerField(default=0, verbose_name='得分'),
        ),
        migrations.AddField(
            model_name='answeredpaper',
            name='StartTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answeredpaper',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='sourcePaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.answeredpaper'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='sourceQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.questionbank'),
        ),
    ]
