# Generated by Django 4.0.3 on 2022-04-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0046_alter_users_managers_users_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
