# Generated by Django 4.0.3 on 2022-04-27 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0047_remove_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Assistant_Teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
